### ISSUE TITLE
Usage of patches2im.m

### ISSUE THREAD

**Issue by Siyeong-Lee** [tsogkas/utils#1]
First, Thanks to your code!

I want to image reconstruction using im2patches.m and patches2im.m.
but I don't know how to use these functions

e.g)
input: image (size: 160,130,3)
[patches , imcol, I]= im2patches(image, 64, 10)
patches2img(patches, size(I), 10)

but do not reconstruct original image...

Please help...

**Comment by tsogkas** [comment]
Hi @Tars-Pinokio , at this moment I think that the function only reconstructs the original image when the stride in im2patches() is selected in such a way that patches are not overlapping (essentially stride == patchsize).
